parameters:
  web_image_name: rhel8
  db_image_name: rhel8
  web_instance_name: heat-web1
  db_instance_name: heat-db1
  instance_flavor: demo-flavor
  key_name: demo-keypair
  public_net: provider-datacentre
  private_net: demo-network
  private_subnet: demo-subnet
